# Name of workflow
name: Dev Test workflow

# Trigger workflow on push and pull requests
on:
   pull_request:
    branches:
      - develop
      - staging

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    # Steps in job
    steps:
      # Get code from repo
      - name: ğŸ§‘â€ğŸ’» Checkout code
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      # Install dependencies
      - name: ğŸ§° Install Deps
        run: npm install

      # Run the build
      - name: ğŸ› ï¸ Build
        run: npm run build

      # Start the server
      - name: ğŸï¸ Start Server
        run: npm run start &
        env:
          PORT: 3001
          MONGODB_URI: mongodb://127.0.0.1:27017/techquiz

      # Wait for the server to be ready
      - name: ğŸ•œ Wait for Server
        run: npx wait-on http://localhost:3001

      # Run Cypress tests
      - name: ğŸ§ª Run Cypress Tests
        run: npm run test-component